CONFIG_CPP=y

CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_TCP=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_DHCPV4=y
CONFIG_NET_HOSTNAME_ENABLE=y
CONFIG_DNS_RESOLVER=y

CONFIG_MQTT_LIB=y
CONFIG_MQTT_VERSION_5_0=y

CONFIG_LOG=y
CONFIG_PRINTK=y
