CONFIG_PJLIB_UTIL=y
CONFIG_PJMEDIA=y
CONFIG_PJMEDIA_SDP=y
CONFIG_PJMEDIA_SDP_NEG=y
CONFIG_PJMEDIA_ENDPOINT=n
CONFIG_PJMEDIA_G711=n
CONFIG_PJMEDIA_RTP_RTCP=n
CONFIG_PJMEDIA_UDP_TRANSPORT=n
CONFIG_PJMEDIA_STREAM=n
CONFIG_PJMEDIA_AUDIODEV=n
CONFIG_PJSIP=n
CONFIG_PJSIP_INVITE=n

CONFIG_PJMEDIA_PHASE1_BOUNDARY_TEST=n
CONFIG_PJMEDIA_PHASE2_SDP_TEST=n
CONFIG_PJMEDIA_PHASE3_SDP_NEG_TEST=n
CONFIG_PJMEDIA_PHASE3_LINK_PROBE=y

CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_MAIN_STACK_SIZE=24576
