CONFIG_PJLIB_UTIL=y
CONFIG_PJMEDIA=y
CONFIG_PJMEDIA_SDP=y
CONFIG_PJMEDIA_SDP_NEG=y
CONFIG_PJSIP=y
CONFIG_PJSIP_INVITE=y
CONFIG_PJSIP_REGC=y
CONFIG_PJSIP_UDP_TRANSPORT=y
CONFIG_PJSIP_TCP_TRANSPORT=n

CONFIG_NET_IPV6=n
CONFIG_NET_LOOPBACK=y

CONFIG_PJMEDIA_ENDPOINT=n
CONFIG_PJMEDIA_G711=n
CONFIG_PJMEDIA_RTP_RTCP=n
CONFIG_PJMEDIA_UDP_TRANSPORT=n
CONFIG_PJMEDIA_STREAM=n
CONFIG_PJMEDIA_AUDIODEV=n

CONFIG_PJMEDIA_PHASE1_BOUNDARY_TEST=n
CONFIG_PJMEDIA_PHASE2_SDP_TEST=n
CONFIG_PJMEDIA_PHASE3_SDP_NEG_TEST=n
CONFIG_PJMEDIA_PHASE3_LINK_PROBE=n
CONFIG_PJMEDIA_PHASE4_INVITE_TEST=n
CONFIG_PJMEDIA_PHASE5_LOOP_CALL_TEST=n
CONFIG_PJMEDIA_PHASE6_UDP_CALL_TEST=y

CONFIG_NET_MAX_CONTEXTS=40
CONFIG_NET_MAX_CONN=40
CONFIG_ZVFS_OPEN_MAX=48
CONFIG_ZVFS_POLL_MAX=40
CONFIG_NET_BUF_DATA_SIZE=256
CONFIG_NET_BUF_RX_COUNT=32
CONFIG_NET_BUF_TX_COUNT=32
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16

CONFIG_HEAP_MEM_POOL_SIZE=524288
CONFIG_MAIN_STACK_SIZE=32768
CONFIG_DYNAMIC_THREAD_POOL_SIZE=10
CONFIG_DYNAMIC_THREAD_STACK_SIZE=8192
CONFIG_MAX_PTHREAD_MUTEX_COUNT=64
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
