CONFIG_PJLIB_UTIL=y
CONFIG_PJMEDIA=y
CONFIG_PJMEDIA_SDP=y
CONFIG_PJMEDIA_SDP_NEG=n
CONFIG_PJMEDIA_ENDPOINT=y
CONFIG_PJMEDIA_G711=n
CONFIG_PJMEDIA_RTP_RTCP=y
CONFIG_PJMEDIA_UDP_TRANSPORT=n
CONFIG_PJMEDIA_STREAM=n
CONFIG_PJMEDIA_AUDIODEV=n
CONFIG_PJMEDIA_AUDIODEV_NULL=n
CONFIG_PJMEDIA_AUDIODEV_ZEPHYR=n

CONFIG_PJSIP=n
CONFIG_PJSIP_INVITE=n
CONFIG_PJSIP_REGC=n
CONFIG_PJSIP_UDP_TRANSPORT=n
CONFIG_PJSIP_TCP_TRANSPORT=n

CONFIG_PJMEDIA_PHASE8_PACKET_TEST=y

CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_MAIN_STACK_SIZE=24576
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
