CONFIG_CPP=y
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_VOIP_FACADE=n
CONFIG_VOIP_SERVICE=y
CONFIG_VOIP_SERVICE_FAKE_ADAPTER=y
CONFIG_VOIP_CORE_SERVICE_TEST=y
CONFIG_VOIP_FAKE_BACKEND=n
CONFIG_VOIP_PHASE1_TEST=n
CONFIG_MAIN_STACK_SIZE=16384
