CONFIG_VOIP_PHASE5_CALL_TEST=n
CONFIG_VOIP_PHASE8_HOLD_RECOVERY_TEST=y
CONFIG_VOIP_PJ_HEADLESS_MEDIA=y

CONFIG_NET_UDP=y
CONFIG_NET_MAX_CONTEXTS=44
CONFIG_NET_MAX_CONN=52
CONFIG_ZVFS_OPEN_MAX=52
CONFIG_ZVFS_POLL_MAX=44
CONFIG_NET_BUF_RX_COUNT=72
CONFIG_NET_BUF_TX_COUNT=72
CONFIG_NET_PKT_RX_COUNT=36
CONFIG_NET_PKT_TX_COUNT=36

CONFIG_PJMEDIA_G711=y
CONFIG_PJMEDIA_RTP_RTCP=y
CONFIG_PJMEDIA_LOOP_TRANSPORT=y
CONFIG_PJMEDIA_UDP_TRANSPORT=y
CONFIG_PJMEDIA_STREAM=y
CONFIG_PJMEDIA_AUDIODEV=n

CONFIG_HEAP_MEM_POOL_SIZE=2097152
CONFIG_MAIN_STACK_SIZE=49152
