CONFIG_VOIP_FAKE_BACKEND=n
CONFIG_VOIP_PJ_BACKEND=y
CONFIG_VOIP_PHASE1_TEST=n
CONFIG_VOIP_PHASE2_RUNTIME_TEST=y

CONFIG_POSIX_API=y
CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_POOL_SIZE=8
CONFIG_DYNAMIC_THREAD_STACK_SIZE=8192
CONFIG_MAX_PTHREAD_MUTEX_COUNT=64

CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_LOOPBACK=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_NET_QEMU_SLIP=n
CONFIG_NET_SLIP_TAP=n
CONFIG_SLIP=n

CONFIG_NET_MAX_CONTEXTS=24
CONFIG_NET_MAX_CONN=24
CONFIG_ZVFS_OPEN_MAX=32
CONFIG_ZVFS_POLL_MAX=24
CONFIG_NET_BUF_DATA_SIZE=256
CONFIG_NET_BUF_RX_COUNT=32
CONFIG_NET_BUF_TX_COUNT=32
CONFIG_NET_PKT_RX_COUNT=16
CONFIG_NET_PKT_TX_COUNT=16

CONFIG_PJPROJECT=y
CONFIG_PJLIB=y
CONFIG_PJLIB_UTIL=y
CONFIG_PJSIP=y
CONFIG_PJSIP_TCP_TRANSPORT=y
CONFIG_PJSIP_UDP_TRANSPORT=n
CONFIG_PJSIP_INVITE=n
CONFIG_PJMEDIA=y
CONFIG_PJMEDIA_SDP=y
CONFIG_PJMEDIA_SDP_NEG=n
CONFIG_PJMEDIA_ENDPOINT=y
CONFIG_PJMEDIA_G711=n
CONFIG_PJMEDIA_RTP_RTCP=n
CONFIG_PJMEDIA_LOOP_TRANSPORT=n
CONFIG_PJMEDIA_UDP_TRANSPORT=n
CONFIG_PJMEDIA_STREAM=n
CONFIG_PJMEDIA_AUDIODEV=n

CONFIG_HEAP_MEM_POOL_SIZE=393216
CONFIG_MAIN_STACK_SIZE=24576
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
