CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_SERIAL=y
CONFIG_CPP=y
CONFIG_GLIBCXX_LIBCPP=y
CONFIG_PICOLIBC=y
CONFIG_VOIP_FACADE=y
CONFIG_VOIP_FAKE_BACKEND=y
CONFIG_VOIP_PHASE1_TEST=y
CONFIG_VOIP_PHASE2_RUNTIME_TEST=n
CONFIG_VOIP_PHASE3_ACCOUNT_TEST=n
CONFIG_MAIN_STACK_SIZE=16384
